package hey

import (
	"fmt"
)

type JoinType string

const (
	JoinMaster JoinType = "MASTER"
	JoinInner           = "INNER"
	JoinLeft            = "LEFT"
	JoinRight           = "RIGHT"
	JoinFull            = "FULL"
)

type Joiner interface {
	// Alias set current table alias name
	Alias(alias string) Joiner
	// OnEqual the criteria for joining the current table query
	OnEqual(left string, right string) Joiner
	// Filter join query additional filtering criteria
	Filter(filter Filter) Joiner
	// Query specify the fields to be queried in this table
	Query(field ...string) Joiner
	// Table name of table
	Table() string
	// Using exposes the final table name used, alias name first
	Using() string
	// F for get table_name.column; (email => a.email | email => account.email)
	F(field string) string
	// Result the current table joins the final sql script and parameters generated by the query
	Result() (prepare string, args []interface{})
	// Select list of fields for the current table query
	Select() []string
}

type Join struct {
	style  JoinType
	table  string
	alias  string
	on     string
	filter Filter
	query  []string
	using  string
}

func (s *Join) Alias(alias string) Joiner {
	if alias != "" {
		s.alias = alias
		s.using = alias
	}
	return s
}

func (s *Join) OnEqual(left string, right string) Joiner {
	s.on = fmt.Sprintf("%s = %s", left, right)
	return s
}

func (s *Join) Filter(filter Filter) Joiner {
	s.filter = filter
	return s
}

func (s *Join) Query(query ...string) Joiner {
	s.query = query
	return s
}

func (s *Join) Table() string {
	return s.table
}

func (s *Join) Using() string {
	return s.using
}

func (s *Join) F(field string) string {
	return fmt.Sprintf("%s.%s", s.using, field)
}

func (s *Join) Result() (prepare string, args []interface{}) {
	if s.style == JoinMaster || s.table == "" || s.on == "" {
		return
	}
	prepare = fmt.Sprintf("%s JOIN %s", s.style, s.table)
	if s.alias != "" {
		prepare = fmt.Sprintf("%s AS %s", prepare, s.alias)
	}
	prepare = fmt.Sprintf("%s ON %s", prepare, s.on)
	if s.filter != nil {
		key, val := s.filter.Result()
		if key != "" {
			prepare = fmt.Sprintf("%s AND %s", prepare, key)
			args = val
		}
	}
	return
}

func (s *Join) Select() (result []string) {
	length := len(s.query)
	result = make([]string, length)
	result = make([]string, len(s.query))
	for i := 0; i < length; i++ {
		result[i] = s.F(s.query[i])
	}
	return
}

func initMaster(table string) Joiner {
	return &Join{
		style: JoinMaster,
		table: table,
		using: table,
	}
}

func MasterTable(table string) Joiner {
	return initMaster(table)
}

func initSlave(style JoinType, table string) Joiner {
	return &Join{
		style: style,
		table: table,
		using: table,
	}
}

func InnerJoin(table string) Joiner {
	return initSlave(JoinInner, table)
}

func LeftJoin(table string) Joiner {
	return initSlave(JoinLeft, table)
}

func RightJoin(table string) Joiner {
	return initSlave(JoinRight, table)
}

func FullJoin(table string) Joiner {
	return initSlave(JoinFull, table)
}
