package cst

const (
	BEGIN     = "BEGIN"
	COMMIT    = "COMMIT"
	ROLLBACK  = "ROLLBACK"
	NULL      = "NULL"
	ALL       = "ALL"
	ANY       = "ANY"
	AS        = "AS"
	ASC       = "ASC"
	DESC      = "DESC"
	UNION     = "UNION"
	INTERSECT = "INTERSECT"
	EXCEPT    = "EXCEPT"
	JOIN      = "JOIN"
	INNER     = "INNER"
	LEFT      = "LEFT"
	RIGHT     = "RIGHT"
	ON        = "ON"
	AND       = "AND"
	OR        = "OR"
	NOT       = "NOT"
	COALESCE  = "COALESCE"
	DISTINCT  = "DISTINCT"
	SELECT    = "SELECT"
	INSERT    = "INSERT"
	UPDATE    = "UPDATE"
	DELETE    = "DELETE"
	FROM      = "FROM"
	INTO      = "INTO"
	VALUES    = "VALUES"
	SET       = "SET"
	WHERE     = "WHERE"
	RETURNING = "RETURNING"
	BETWEEN   = "BETWEEN"
	CONFLICT  = "CONFLICT"
	DO        = "DO"
	EXCLUDED  = "EXCLUDED"
	EXISTS    = "EXISTS"
	GROUP     = "GROUP"
	BY        = "BY"
	HAVING    = "HAVING"
	IN        = "IN"
	IS        = "IS"
	LIKE      = "LIKE"
	LIMIT     = "LIMIT"
	NOTHING   = "NOTHING"
	OFFSET    = "OFFSET"
	ORDER     = "ORDER"
	OVER      = "OVER"
	PARTITION = "PARTITION"
	USING     = "USING"
	WITH      = "WITH"
	RECURSIVE = "RECURSIVE"
	CASE      = "CASE"
	WHEN      = "WHEN"
	THEN      = "THEN"
	ELSE      = "ELSE"
	END       = "END"
	RANGE     = "RANGE"
	ROWS      = "ROWS"
	COUNT     = "COUNT"
	AVG       = "AVG"
	MAX       = "MAX"
	MIN       = "MIN"
	SUM       = "SUM"
)

const (
	Placeholder      = "?"
	Equal            = "="
	NotEqual         = "<>"
	GreaterThan      = ">"
	GreaterThanEqual = ">="
	LessThan         = "<"
	LessThanEqual    = "<="
	LeftParenthesis  = "("
	RightParenthesis = ")"

	Empty                = ""
	Space                = " "
	Comma                = ","
	Point                = "."
	Plus                 = "+"
	Minus                = "-"
	Asterisk             = "*"
	Slash                = "/"
	Backslash            = "\\"
	Dollar               = "$"
	PercentSign          = "%"
	Semicolon            = ";"
	SingleQuotationMark  = "'"
	SingleQuotationMarks = "''"
	CommaSpace           = Comma + Space
)

const (
	LogId      = "id"
	LogStartAt = "start_at"
	LogEndAt   = "end_at"
	LogState   = "state"
	LogError   = "error"
	LogScript  = "script"
	LogMsg     = "msg"
	LogPrepare = "prepare"
	LogArgs    = "args"
	LogCost    = "cost"
)

const (
	A = "a"
	B = "b"
	C = "c"
	D = "d"
	E = "e"
	F = "f"
	G = "g"

	Id = "id"
)

type DatabaseType string

const (
	Postgresql DatabaseType = "postgresql"
	Sqlite     DatabaseType = "sqlite"
	Mysql      DatabaseType = "mysql"
)
